### ISSUE TITLE
DCOR does not support background images

### ISSUE THREAD

**Issue by B-Hartmann** [DCOR-dev/ckanext-dc_serve#2]
When accessing data on DCOR that has a Shape-In generated "image_bg" via Shape-Out, the following error messages appear. I know that Shape-Out in general can handle background images, it seems to be that the support in DCOR/dclab is incomplete.
```
Unhandled exception in Shape-Out version 2.11.0:
Traceback (most recent call last):
  File "shapeout2\gui\widgets\wait_cursor.py", line 31, in wrapper
    ret = func(*args, **kwargs)
  File "shapeout2\gui\quick_view\qv_main.py", line 530, in plot
    self.on_tool()
  File "shapeout2\gui\widgets\wait_cursor.py", line 31, in wrapper
    ret = func(*args, **kwargs)
  File "shapeout2\gui\quick_view\qv_main.py", line 494, in on_tool
    self.on_event_scatter_update()
  File "shapeout2\gui\quick_view\qv_main.py", line 345, in on_event_scatter_update
    self.show_event(event - 1)
  File "shapeout2\gui\widgets\wait_cursor.py", line 31, in wrapper
    ret = func(*args, **kwargs)
  File "shapeout2\gui\quick_view\qv_main.py", line 567, in show_event
    cellimg, imkw = self.get_event_image(ds, event)
  File "shapeout2\gui\quick_view\qv_main.py", line 245, in get_event_image
    bgimg = ds["image_bg"][event].astype(np.int16)
  File "dclab\rtdc_dataset\fmt_hierarchy.py", line 48, in __getitem__
  File "dclab\rtdc_dataset\fmt_hierarchy.py", line 48, in __getitem__
  File "dclab\rtdc_dataset\core.py", line 91, in __getitem__
  File "dclab\rtdc_dataset\fmt_dcor\features.py", line 169, in __getitem__
ValueError: No DCOR handler for feature 'image_bg'!
```

Might be related to [dclab issue 170](https://github.com/ZELLMECHANIK-DRESDEN/dclab/issues/170).

**Comment by paulmueller** [comment]
This is actually an issue in dclab and is fixed with https://github.com/ZELLMECHANIK-DRESDEN/dclab/commit/981095e2bfcc66974b4f43c33e2a01520a2b8693
